### ISSUE TITLE
Encode list

### ISSUE THREAD

**Issue by cullophid** [BuckleTypes/bs-json#2]
missing the option to encode a list,
currently im doing `let list encoder xs => xs |> List.map encoder |> Array.of_list |> Json.Encode.array`.
It works fine, but support in the lib would be great.

Sorry for not doing a PR, but i haven't quite figured out how the lib works

**Comment by glennsl** [comment]
Hi. Thanks for reporting! It's been somewhat intentionally left out, because of the hidden performance cost and because it would be inconsistent with the signature of `array`. I've added it now anyway though. I'll figure out what to do with `array` later...
